atp_players = [
  {
    first_name: "Novak",
    last_name: "Djokovic",
    country: "Serbia",
    singles_ranking: 1,
    singles_points: 12113,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "961/195",
    career_singles_titles: 85,
    doubles_ranking: 181,
    doubles_points: 540,
    career_doubles_record: "59/73",
    career_doubles_titles: 1,
    racquet_hand: "right",
    backhand: "double",
    height: 188,
    weight: 77,
    age: 34,
    birthday: Date.new(1987,5,22),
    prize_money: 151876636,
    residence: "Monte Carlo, Monaco",
    birthplace: "Belgrade, Serbia",
    coach: ["Marian Vajda", "Goran Ivanisevic"],
    mother: "Dijana Djokovic",
    father: "Srdan Djokovic"
  },
  {
    first_name: "Daniil",
    last_name: "Medvedev",
    country: "Russia",
    singles_ranking: 2,
    singles_points: 10370,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "188/94",
    career_singles_titles: 11,
    doubles_ranking: 238,
    doubles_points: 355,
    career_doubles_record: "13/19",
    career_doubles_titles: 0,
    racquet_hand: "right",
    backhand: "double",
    height: 198,
    weight: 83,
    age: 25,
    birthday: Date.new(1996,2,11),
    prize_money: 16638415,
    residence: "Monte Carlo, Monaco",
    birthplace: "Moscow, Russia",
    coach: ["Gilles Cervara"],
    mother: "Sergey Medvedev",
    father: "Olga Medvedeva"
  },
  {
    first_name: "Rafael",
    last_name: "Nadal",
    country: "Spain",
    singles_ranking: 3,
    singles_points: 8270,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "1027/208",
    career_singles_titles: 88,
    doubles_ranking: 515,
    doubles_points: 95,
    career_doubles_record: "137/74",
    career_doubles_titles: 11,
    racquet_hand: "left",
    backhand: "double",
    height: 185,
    weight: 85,
    age: 35,
    birthday: Date.new(1986,6,3),
    prize_money: 124937195,
    residence: "Manacor, Mallorca, Spain",
    birthplace: "Manacor, Mallorca, Spain",
    coach: ["Carlos Moya, Francisco Roig"],
    mother: "Ana Maria Parera",
    father: "Sebastian Nadal"
  },
  {
    first_name: "Stefanos",
    last_name: "Tsitsipas",
    country: "Greece",
    singles_ranking: 4,
    singles_points: 8150,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "172/86",
    career_singles_titles: 7,
    doubles_ranking: 151,
    doubles_points: 710,
    career_doubles_record: "13/37",
    career_doubles_titles: 0,
    racquet_hand: "right",
    backhand: "single",
    height: 196,
    weight: 90,
    age: 22,
    birthday: Date.new(1987,8,12),
    prize_money: 15116070,
    residence: "Monte Carlo, Monaco",
    birthplace: "Athens, Greece",
    coach: ["Apostolos Tsitsipas"],
    mother: "Julia Salnikova",
    father: "Apostolos Tsitsipas"
  },
  {
    first_name: "Alexander",
    last_name: "Zverev",
    country: "Germany",
    singles_ranking: 5,
    singles_points: 7475,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "278/136",
    career_singles_titles: 15,
    doubles_ranking: 117,
    doubles_points: 950,
    career_doubles_record: "48/53",
    career_doubles_titles: 2,
    racquet_hand: "right",
    backhand: "double",
    height: 198,
    weight: 90,
    age: 24,
    birthday: Date.new(1997,4,20),
    prize_money: 25171770,
    residence: "Monte Carlo, Monaco",
    birthplace: "Hamburg, Germany",
    coach: ["Alexander Zverev Sr."],
    mother: "Irina Zvereva",
    father: "Alexander Zverev Sr."
  },
  {
    first_name: "Dominic",
    last_name: "Thiem",
    country: "Austria",
    singles_ranking: 6,
    singles_points: 7425,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "309/166",
    career_singles_titles: 17,
    doubles_ranking: 208,
    doubles_points: 435,
    career_doubles_record: "39/72",
    career_doubles_titles: 0,
    racquet_hand: "right",
    backhand: "single",
    height: 185,
    weight: 79,
    age: 27,
    birthday: Date.new(1993,9,3),
    prize_money: 28861776,
    residence: "Lichtenworth, Austria",
    birthplace: "Wiener Neustadt, Austria",
    coach: ["Nicolas Massu"],
    mother: "Karin Thiem",
    father: "Wolfgang Thiem"
  },
  {
    first_name: "Andrey",
    last_name: "Rublev",
    country: "Russia",
    singles_ranking: 7,
    singles_points: 6255,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "168/100",
    career_singles_titles: 8,
    doubles_ranking: 75,
    doubles_points: 1660,
    career_doubles_record: "39/45",
    career_doubles_titles: 2,
    racquet_hand: "right",
    backhand: "double",
    height: 188,
    weight: 75,
    age: 23,
    birthday: Date.new(1997,10,20),
    prize_money: 8596780,
    residence: "Moscow, Russia",
    birthplace: "Moscow, Russia",
    coach: ["Fernando Vicente"],
    mother: "Marina Marenko",
    father: "Andrey Rublev Sr."
  },
  {
    first_name: "Matteo",
    last_name: "Berrettini",
    country: "Russia",
    singles_ranking: 8,
    singles_points: 5488,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "103/58",
    career_singles_titles: 5,
    doubles_ranking: 211,
    doubles_points: 425,
    career_doubles_record: "21/16",
    career_doubles_titles: 2,
    racquet_hand: "right",
    backhand: "double",
    height: 196,
    weight: 95,
    age: 25,
    birthday: Date.new(1996,4,12),
    prize_money: 7605702,
    residence: "Monte Carlo, Monaco",
    birthplace: "Rome, Italy",
    coach: ["Vincenzo Santopadre, Marco Gulisano, Umberto Rianna"],
    mother: "Claudia Bigo",
    father: "Luca Berrettini"
  },
  {
    first_name: "Roger",
    last_name: "Federer",
    country: "Switzerland",
    singles_ranking: 9,
    singles_points: 4215,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "1251/275",
    career_singles_titles: 103,
    doubles_ranking: "inactive",
    doubles_points: "inactive",
    career_doubles_record: "131/92",
    career_doubles_titles: 8,
    racquet_hand: "right",
    backhand: "single",
    height: 185,
    weight: 85,
    age: 39,
    birthday: Date.new(1981,8,8),
    prize_money: 130594339,
    residence: "Switzerland",
    birthplace: "Basel, Switzerland",
    coach: ["Ivan Ljubicic, Severin Luthi"],
    mother: "Lynette Federer",
    father: "Robert Federer"
  },
  {
    first_name: "Denis",
    last_name: "Shapovalov",
    country: "Switzerland",
    singles_ranking: 10,
    singles_points: 3625,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "126/101",
    career_singles_titles: 1,
    doubles_ranking: 62,
    doubles_points: 1955,
    career_doubles_record: "34/37",
    career_doubles_titles: 0,
    racquet_hand: "left",
    backhand: "single",
    height: 185,
    weight: 75,
    age: 22,
    birthday: Date.new(1999,4,15),
    prize_money: 7084969,
    residence: "Nassau, Bahamas",
    birthplace: "Tel Aviv, Israel",
    coach: ["Tessa Shapovalova, Mikhail Youzhny"],
    mother: "Tessa Shapovalova",
    father: "Viktor Shapovalova"
  }
]

atp_players.each { |player| NewPlayer.new(player).create }