players = [
  {
    first_name: "Novak",
    last_name: "Djokovic",
    country: "Serbia",
    singles_ranking: 1,
    singles_points: 5170,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "961/195",
    career_singles_titles: 84,
    doubles_ranking: 219,
    doubles_points: 390,
    career_doubles_record: "56/73",
    career_doubles_titles: 11,
    racquet_hand: "right",
    backhand: "double",
    height: 188,
    weight: 77,
    age: 34,
    birthday: Date.new(1987,5,22),
    prize_money: 149798813,
    residence: "Monte Carlo, Monaco",
    birthplace: "Belgrade, Serbia",
    coach: ["Marian Vajda", "Goran Ivanisevic"],
    mother: "Dijana Djokovic",
    father: "Srdan Djokovic"
  },
  {
    first_name: "Stefanos",
    last_name: "Tsitsipas",
    country: "Greece",
    singles_ranking: 4,
    singles_points: 7980,
    association_name: "Association of Tennis Professionals",
    association_acronym: "ATP",
    career_singles_record: "172/85",
    career_singles_titles: 7,
    doubles_ranking: 148,
    doubles_points: 710,
    career_doubles_record: "13/36",
    career_doubles_titles: 0,
    racquet_hand: "right",
    backhand: "single",
    height: 196,
    weight: 90,
    age: 22,
    birthday: Date.new(1987,8,12),
    prize_money: 15050627,
    residence: "Monte Carlo, Monaco",
    birthplace: "Athens, Greece",
    coach: ["Apostolos Tsitsipas"],
    mother: "Julia Salnikova",
    father: "Apostolos Tsitsipas"
  },
  {
    first_name: "Ashleigh",
    last_name: "Barty",
    country: "Australia",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 1,
    singles_points: 8245,
    career_singles_record: "280/100",
    career_singles_titles: 11,
    doubles_ranking: 27,
    doubles_points: 2981,
    career_doubles_record: "195/63",
    career_doubles_titles: 11,
    racquet_hand: "right",
    backhand: "double",
    height: 166,
    weight: 62,
    age: 25,
    birthday: Date.new(1996,4,24),
    prize_money: 1203735,
    residence: "Ipswich, Australia",
    birthplace: "Ipswich, Australia",
    coach: ["Craig Tyzzer"],
    mother: "Josie Barty",
    father: "Robert Barty"
  }
]

players.each { |player| NewPlayer.new(player).create }