wta_players = [
  {
    first_name: "Ashleigh",
    last_name: "Barty",
    country: "Australia",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 1,
    singles_points: 9635,
    career_singles_record: "287/100",
    career_singles_titles: 12,
    doubles_ranking: 36,
    doubles_points: 2666,
    career_doubles_record: "195/63",
    career_doubles_titles: 11,
    racquet_hand: "right",
    backhand: "double",
    height: 166,
    weight: 62,
    age: 25,
    birthday: Date.new(1996,4,24),
    prize_money: 21104531,
    residence: "Ipswich, Australia",
    birthplace: "Ipswich, Australia",
    coach: ["Craig Tyzzer"],
    mother: "Josie Barty",
    father: "Robert Barty"
  },
  {
    first_name: "Naomi",
    last_name: "Osaka",
    country: "Japan",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 2,
    singles_points: 7336,
    career_singles_record: "247/136",
    career_singles_titles: 7,
    doubles_ranking: "inactive",
    doubles_points: "inactive",
    career_doubles_record: "2/14",
    career_doubles_titles: 0,
    racquet_hand: "right",
    backhand: "double",
    height: 180,
    weight: 74,
    age: 23,
    birthday: Date.new(1997,10,16),
    prize_money: 19872256,
    residence: "Beverly Hills, California",
    birthplace: "Osaka, Japan",
    coach: ["Wim Fissette"],
    mother: "Leonard Francois",
    father: "Tamaki Osaka"
  },
  {
    first_name: "Aryna",
    last_name: "Sabalenka",
    country: "Belarus",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 3,
    singles_points: 6965,
    career_singles_record: "261/131",
    career_singles_titles: 10,
    doubles_ranking: 6,
    doubles_points: 7595,
    career_doubles_record: "84/62",
    career_doubles_titles: 6,
    racquet_hand: "right",
    backhand: "double",
    height: 182,
    weight: 79,
    age: 23,
    birthday: Date.new(1998,5,5),
    prize_money: 8684783,
    residence: "Minsk, Belarus",
    birthplace: "Minsk, Belarus",
    coach: ["Anton Dubrov"],
    mother: "n/a",
    father: "Sergey Sabalenka"
  },
  {
    first_name: "Sofia",
    last_name: "Kenin",
    country: "United States",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 4,
    singles_points: 5640,
    career_singles_record: "225/130",
    career_singles_titles: 5,
    doubles_ranking: 33,
    doubles_points: 2760,
    career_doubles_record: "64/55",
    career_doubles_titles: 2,
    racquet_hand: "right",
    backhand: "double",
    height: 170,
    weight: 57,
    age: 22,
    birthday: Date.new(1998,11,14),
    prize_money: 7733926,
    residence: "Pembroke Pines, Florida, U.S.",
    birthplace: "Moscow, Russia",
    coach: ["Self-coached"],
    mother: "Lena Kenin",
    father: "Alex Kenin"
  },
  {
    first_name: "Bianca",
    last_name: "Andreescu",
    country: "Canada",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 5,
    singles_points: 5331,
    career_singles_record: "149/57",
    career_singles_titles: 3,
    doubles_ranking: 1276,
    doubles_points: 11,
    career_doubles_record: "29/17",
    career_doubles_titles: 0,
    racquet_hand: "right",
    backhand: "double",
    height: 170,
    weight: 60,
    age: 21,
    birthday: Date.new(2000,6,16),
    prize_money: 7167407,
    residence: "Thornhill, Ontario, Canada",
    birthplace: "Mississauga, Ontario, Canada",
    coach: ["Sylvain Bruneau"],
    mother: "Maria Andreescu",
    father: "Nicu Andreescu"
  },
  {
    first_name: "Elina",
    last_name: "Svitolina",
    country: "Ukraine",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 6,
    singles_points: 5125,
    career_singles_record: "410/213",
    career_singles_titles: 15,
    doubles_ranking: 659,
    doubles_points: 74,
    career_doubles_record: "48/67",
    career_doubles_titles: 2,
    racquet_hand: "right",
    backhand: "double",
    height: 174,
    weight: 59,
    age: 26,
    birthday: Date.new(1994,9,12),
    prize_money: 20566678,
    residence: "London, England",
    birthplace: "Odessa, Ukraine",
    coach: ["Andrew Bettles"],
    mother: "Olena Svitolina",
    father: "Mikhaylo Svitolin"
  },
  {
    first_name: "Karolina",
    last_name: "Pliskova",
    country: "Czech Republic",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 7,
    singles_points: 4975,
    career_singles_record: "562/310",
    career_singles_titles: 16,
    doubles_ranking: 68,
    doubles_points: 1551,
    career_doubles_record: "177/138",
    career_doubles_titles: 5,
    racquet_hand: "right",
    backhand: "double",
    height: 186,
    weight: 69,
    age: 29,
    birthday: Date.new(1992,3,21),
    prize_money: 22194804,
    residence: "Monte Carlo, Monaco",
    birthplace: "Louny, Czech Republic",
    coach: ["Sascha Bajin"],
    mother: "Martina Pliskova",
    father: "Radek Plisek"
  },
  {
    first_name: "Iga",
    last_name: "Swiatek",
    country: "Poland",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 8,
    singles_points: 4695,
    career_singles_record: "137/39",
    career_singles_titles: 3,
    doubles_ranking: 44,
    doubles_points: 2290,
    career_doubles_record: "24/12",
    career_doubles_titles: 0,
    racquet_hand: "right",
    backhand: "double",
    height: 176,
    weight: 69,
    age: 20,
    birthday: Date.new(2001,5,31),
    prize_money: 4211123,
    residence: "Raszyn, Poland",
    birthplace: "Warsaw, Poland",
    coach: ["Piotr Sierzputowski"],
    mother: "Dorota Swiatek",
    father: "Tomasz Swiatek"
  },
  {
    first_name: "Simona",
    last_name: "Halep",
    country: "Romania",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 9,
    singles_points: 4330,
    career_singles_record: "527/222",
    career_singles_titles: 22,
    doubles_ranking: 224,
    doubles_points: 399,
    career_doubles_record: "66/67",
    career_doubles_titles: 1,
    racquet_hand: "right",
    backhand: "double",
    height: 168,
    weight: 59,
    age: 29,
    birthday: Date.new(1991,9,27),
    prize_money: 4211123,
    residence: "Constanta, Romania",
    birthplace: "Constanta, Romania",
    coach: ["Darren Cahill"],
    mother: "Tania Halep",
    father: "Stere Halep"
  },
  {
    first_name: "Garbine",
    last_name: "Muguruza",
    country: "Spain",
    association_name: "Women's Tennis Association",
    association_acronym: "WTA",
    singles_ranking: 10,
    singles_points: 4165,
    career_singles_record: "422/210",
    career_singles_titles: 8,
    doubles_ranking: 343,
    doubles_points: 221,
    career_doubles_record: "81/49",
    career_doubles_titles: 5,
    racquet_hand: "right",
    backhand: "double",
    height: 182,
    weight: 73,
    age: 27,
    birthday: Date.new(1993,10,8),
    prize_money: 4211123,
    residence: "Geneva, Switzerland",
    birthplace: "Caracas, Venezuela",
    coach: ["Conchita Martinez"],
    mother: "Scarlet Blanco",
    father: "Jose Antonio Muguruza"
  }
]

wta_players.each { |player| NewPlayer.new(player).create }